version: "3.8"
services:
    xcoin_backend:
      build: 
        context: .
        dockerfile: ./Dockerfile
      stop_signal: SIGINT
      container_name: xcoin_api_service
      image: xcoin_backend
      ports:
        - "3000:3000"
      # ? For automatically updating the container (for development only)
      volumes:
        - .:/app
      restart: always

    xcoin_database:
      image: mongo
      container_name: xcoin_db_service
      ports:
        - "27017:27017"
      volumes:
        - /data/db:/data/db
      restart: unless-stopped